services:
  - type: web
    name: yowauth-poc
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: IWM_MANAGEMENT_API_KEY
        generateValue: true
      - key: IWM_POC_CLIENT_SECRET
        sync: false
      - key: IWM_CORS_ALLOWED_ORIGINS
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: "-XX:MaxRAMPercentage=65"
